name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: hieuphiacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Spring Boot image
        run: |
          cd backend
          docker build -t hieuphiacr.azurecr.io/springboot:v1 .
          docker push hieuphiacr.azurecr.io/springboot:v1

      - name: Build and push Flask image
        run: |
          cd ../flask-service
          docker build -t hieuphiacr.azurecr.io/flask:v1 .
          docker push hieuphiacr.azurecr.io/flask:v1